name: Backend CI/CD

on:
  push:
    branches: [ "main", "develop", "refacto/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      # On peut même ajouter une BDD PostgreSQL pour les tests d'intégration
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check backend/app

      - name: Run tests with Pytest
        env:
          # On surcharge l'URL de la BDD pour pointer vers le service postgres
          DATABASE_URL: "postgresql+asyncpg://testuser:testpassword@localhost:5432/testdb"
        run: |
          pytest backend/tests
